# SonarQube project configuration
sonar.projectKey=learn-testing
sonar.projectName=Learn Testing
sonar.organization=sonalyze

# Source code directories
sonar.sources=backend
sonar.tests=backend
sonar.test.inclusions=**/*_test.go

# Exclusions
sonar.exclusions=node_modules/**,reports/**,logs/**,env/**,script/**,coverage/**,frontend/**,server/**

# Go specific settings
sonar.go.coverage.reportPaths=backend/coverage.out

# Additional settings
sonar.sourceEncoding=UTF-8
