#!/usr/bin/env bash

# script/test: Run Go backend tests.

# Exit immediately if an error occurs
set -euo pipefail

# Go to the project directory
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo '==> Running Go backend tests...'
go test ./backend -v -cover -coverprofile=backend/coverage.out
